BaseURL: 'https://www.mywebsite.com/'
languageCode: en-us
title: Kronbot
theme: default
relativeURLS: true
description: descriere
module:
  mounts:
    - source: node_modules/bootstrap/dist/js/bootstrap.bundle.min.jss
      target: assets/js/bootstrap.bundle.min.js
    - source: node_modules/bootstrap/dist/js/bootstrap.bundle.min.js
      target: assets/js/bootstrap.bundle.min.js

DefaultContentLanguage: en
languages:
  en:
    languageName: English
    weight: 1
  ro:
    languageName: Romana
    weight: 2
